artifacts_root: artifacts


data_ingestion:
  bucket_name: "helmet-object-detection-20112023"
  zip_file_name: "Chest-CT-Scan-data.zip"
  root_dir: artifacts/data_ingestion
  # local_data_file: "artifacts/data_ingestion/Chest-CT-Scan-data-new.zip"
  local_data_file: Chest-CT-Scan-data.zip
  # unzip_dir: artifacts\data_ingestion
  unzip_dir: artifacts/data_ingestion
  adenocarcinoma_dir: artifacts/data_ingestion/Chest-CT-Scan-data/adenocarcinoma
  normal_dir: artifacts/data_ingestion/Chest-CT-Scan-data/normal

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5

aws_access_key:
  aws_access_key_id_env_key: "AWS_ACCESS_KEY_ID"
  aws_secret_access_key_env_key: "AWS_SECRET_ACCESS_KEY"
  region_name: "us-east-1"

